server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/iminayad/microservice_java.git
          default-label: main
          search-paths: config-data
#          username: iminayad
#          password: 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